# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthscorefactors',
            name='capacity_total_freePct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='cpuLatestTotalAvgPct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='cpuLatestTotalMaxPct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='ddsSizeUsedTiB',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='delAcksPct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='healthscore',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='nodeCountMissing',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='nodeCountOffline',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='portReadBandwidthMBPS',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscorefactors',
            name='portWriteBandwidthMBPS',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
