# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='healthscore',
        ),
    ]
