# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170215_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Server'),
        ),
    ]
