# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_server_healthscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='healthscore',
            field=models.IntegerField(default=100),
        ),
    ]
