# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_serverrecord_todatetimefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrecord',
            name='fromDateTimeField',
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='fromDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='toDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
