# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_server_healthscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='healthscore',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
