# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170406_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='system_companyName',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
