# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170215_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrecord',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='records',
            field=models.ManyToManyField(to='dashboard.ServerRecord'),
        ),
    ]
