# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170426_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthscoreFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemId', models.CharField(db_index=True, default='0', max_length=128)),
                ('healthscore', models.IntegerField(default=100)),
                ('capacity_total_freePct', models.IntegerField(default=0)),
                ('delAcksPct', models.IntegerField(default=0)),
                ('portReadBandwidthMBPS', models.IntegerField(default=0)),
                ('portWriteBandwidthMBPS', models.IntegerField(default=0)),
                ('cpuLatestTotalAvgPct', models.IntegerField(default=0)),
                ('cpuLatestTotalMaxPct', models.IntegerField(default=0)),
                ('nodeCountOffline', models.IntegerField(default=0)),
                ('nodeCountMissing', models.IntegerField(default=0)),
                ('ddsSizeUsedTiB', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'healthscore_factors',
            },
        ),
        migrations.AlterField(
            model_name='server',
            name='healthscore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.HealthscoreFactors'),
        ),
    ]
