# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170412_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='systemId',
            field=models.CharField(db_index=True, default='0', max_length=128),
        ),
    ]
