# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170216_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='servers',
            field=models.ManyToManyField(to='dashboard.Server'),
        ),
    ]
