# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_merge_20170412_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverrecord',
            options={'ordering': ['toDate']},
        ),
    ]
