# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170217_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrecord',
            name='fromDateField',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverrecord',
            name='toDateTimeField',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='fromDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
