# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170218_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverrecord',
            old_name='fromDateField',
            new_name='fromDateTimeField',
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='fromDate',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
