# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170218_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['serialNumberInserv']},
        ),
        migrations.AddField(
            model_name='server',
            name='updatedDateField',
            field=models.DateField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
