# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170220_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='id',
        ),
        migrations.RemoveField(
            model_name='server',
            name='updatedDateField',
        ),
        migrations.AlterField(
            model_name='server',
            name='serialNumberInserv',
            field=models.CharField(default='0', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='systemId',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
