# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20170405_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='records',
        ),
    ]
