# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_server_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateField(blank=True, max_length=128, null=True),
        ),
    ]
